# Generated by Django 5.1.1 on 2024-10-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driver_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('license_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drivers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyServices',
            fields=[
                ('service_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('service_type', models.CharField(blank=True, max_length=50, null=True)),
                ('response_time', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('availability_status', models.IntegerField(blank=True, null=True)),
                ('service_area', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'emergency_services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingLots',
            fields=[
                ('parking_lot_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('available_spaces', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parking_lots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('road_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('lane_count', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('congestion_level', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('length_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_speed_limit', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'roads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TollBooths',
            fields=[
                ('toll_booth_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('toll_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('collected_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('last_collection_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'toll_booths',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrafficCameras',
            fields=[
                ('camera_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('camera_type', models.CharField(blank=True, max_length=50, null=True)),
                ('active_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'traffic_cameras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrafficIncidents',
            fields=[
                ('incident_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('response_time', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('severity_level', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'traffic_incidents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrafficLights',
            fields=[
                ('light_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('current_status', models.CharField(blank=True, max_length=15, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('operation_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('maintenance_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'traffic_lights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicle_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('insurance_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrafficViolation',
            fields=[
                ('violation_id', models.AutoField(primary_key=True, serialize=False)),
                ('violation_type', models.CharField(max_length=50)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('violation_date', models.DateField()),
                ('violation_time', models.TimeField()),
                ('penalty_points', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'traffic_violations',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
