# Generated by Django 5.1.1 on 2024-10-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_drivers_emergencyservices_parkinglots_roads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficviolation',
            name='fine_amount',
            field=models.IntegerField(),
        ),
    ]
