# Generated by Django 5.1.1 on 2024-10-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_trafficviolation_fine_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficviolation',
            name='violation_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
